- name: "Debian 9, 10 or 11 required"
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version in [ "9", "10", "11" ]
    msg: "Only Debian 9, 10 and 11 is supported, this is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

- name: "install package chrony"
  apt:
    name: chrony
    state: present

- name: "Enable/disable default pool"
  lineinfile:
    path: /etc/chrony/chrony.conf
    search_string: 'pool 2.debian.pool.ntp.org iburst'
    line: '{{ "#" if ntp_disable_default_pool  else ""  }}pool 2.debian.pool.ntp.org iburst'

- name: "add ntp servers"
  blockinfile:
    path: /etc/chrony/chrony.conf
    block: "{{ ntp_servers }}"
    insertbefore: "# Use Debian vendor zone."
  register: chronyconf

- name: "restart chronyd"
  when: chronyconf.changed
  service:
    name: chronyd
    state: restarted
