- name: "Debian/Ubuntu check"
  assert:
    that:
      - ansible_facts['distribution'] in ["Debian", "Ubuntu", "Linux Mint"]
      - (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] is version('10', '>=')) or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] is version('20', '>=')) or
        (ansible_facts['distribution'] == "Linux Mint" and ansible_facts['distribution_major_version'] is version('21', '>='))
    fail_msg: "Required Debian version is 10 or Ubuntu version is 20. This is {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}"
    quiet: true

- name: "install package chrony"
  apt:
    name: chrony
    state: present

- name: "enable/disable default Debian pool"
  when: ansible_facts['distribution'] == "Debian"
  lineinfile:
    path: /etc/chrony/chrony.conf
    search_string: 'pool 2.debian.pool.ntp.org iburst'
    line: '{{ "#" if ntp_disable_default_pool  else ""  }}pool 2.debian.pool.ntp.org iburst'

- name: "clean up older config"
  blockinfile:
    path: /etc/chrony/chrony.conf
    state: absent

- name: "add ntp servers"
  copy:
    dest: /etc/chrony/sources.d/cesnet.sources
    content: "{{ ntp_servers }}"
  register: chronyconf

- name: "restart chronyd"
  when: chronyconf.changed
  ansible.builtin.service:
    name: chronyd
    state: restarted

