- name: "Debian version check"
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version is version('10','>=')
    msg: "Required version is 10, this is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
    quiet: true

- name: "install package chrony"
  apt:
    name: chrony
    state: present

- name: "Enable/disable default pool"
  lineinfile:
    path: /etc/chrony/chrony.conf
    search_string: 'pool 2.debian.pool.ntp.org iburst'
    line: '{{ "#" if ntp_disable_default_pool  else ""  }}pool 2.debian.pool.ntp.org iburst'

- name: "add ntp servers"
  blockinfile:
    path: /etc/chrony/chrony.conf
    block: "{{ ntp_servers }}"
    insertbefore: "# Use Debian vendor zone."
  register: chronyconf

- name: "restart chronyd"
  when: chronyconf.changed
  service:
    name: chronyd
    state: restarted
